lang: en
#subtitle: "æ•™æè¡¥å……è§£é‡Šä¸è¯´æ˜"
title-slide-attributes:
    data-background-image: https://assets.qiufei.site/zwu/nice_to_meet_you.png
    data-background-size: contain
    data-background-opacity: "0.5"
author: "peter(é‚±é£)"
institute: "zhejiang wanli university"

format:
  revealjs:
    width: 1280
    height: 720
    slide-level: 4
    slide-number: true
    show-slide-number: all
    fig-align: center
    #smaller: true
    theme: serif
    logo: zwu_logo.png
    embed-resources: true
    footer: "é‚±é£(peter) ğŸ’Œ qiufei@zwu.edu.cn"
    scrollable: true
    css: my.css


execute: 
  eval: true
  echo: false
  warning: false 